const data = {
  products: [
    {
      _id: "1",
      name: "Honky Bonky 1",
      category: "Geese",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Honk",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Goose",
    },
    {
      _id: "2",
      name: "Honky Bonky 2",
      category: "Geese",
      image: "/images/p2.jpg",
      price: 100,
      brand: "Goose",
      rating: 4.0,
      numReviews: 10,
      description: "high quality Honk",
    },
    {
      _id: "3",
      name: "Honky Bonky 3",
      category: "Geese",
      image: "/images/p3.jpg",
      price: 220,
      brand: "Bonks",
      rating: 3,
      numReviews: 17,
      description: "high quality Bonk",
    },
    {
      _id: "4",
      name: "Quack Pack 1",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      brand: "Honk",
      rating: 3.5,
      numReviews: 14,
      description: "high quality Quack",
    },
    {
      _id: "5",
      name: "Quack Pack 2",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      brand: "Goose",
      rating: 4.8,
      numReviews: 10,
      description: "high quality kaaak",
    },
    {
      _id: "6",
      name: "Quack Pack 3",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      brand: "Bonk",
      rating: 2.5,
      numReviews: 15,
      description: "high quality Bonk",
    },
  ],
};
export default data;
